version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      MONGO_DB: ${MONGO_DB} 
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
